### PR TITLE
chore: port searchParams.ts

### LINKED ISSUE #24: port `searchParams.ts` - trivial

### PR DESCRIPTION
**Pull request by MengLinMaker**
Closes #24

### CODE REVIEW

**Comment by MengLinMaker** [comment]
@fteodoro803 I've opened a PR from your branch to main.

The CI will auto format the code.

**Comment by fteodoro803** [comment]
I looked around yesterday and I didnt see any. But i'll have a second look now!

Also I'll delete the old searchParams in the next commit

**Comment by MengLinMaker** [comment]
@fteodoro803 merge PR when you are ready

**Comment by fteodoro803** [comment]
@MengLinMaker I just committed with the deleted file. I also saw nothing in the tests. I'll merge now

**Comment by fteodoro803** [comment]
@MengLinMaker I think my commit is making it need a second review before we can squash and merge hahaha

**Review by MengLinMaker — COMMENTED** [review]
Trying to approve

@fteodoro803 I cannot review. I think you need to?

Otherwise just bypass I guess.

Or I'll turn off needing to review

**Pull request merged**
